version: '3'

services:

  app:
    container_name: app
    image: node:18-alpine
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      TZ: UTC
    command: >
      sh -c "
        yarn &&
        yarn start:dev
      "

  db:
    container_name: db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      TZ: UTC
    volumes:
      - ./db/data:/var/lib/postgresql/data

  tbls:
    image: k1low/tbls
    working_dir: /work
    volumes:
      - ./:/work
    command: doc
    depends_on:
      - db
